FROM jenkins:latest

# install tools with root user
USER root
{% if apt_packages is defined %}
RUN apt-get update && apt-get install -y {% for apt_package in apt_packages %}{{ apt_package }} {% endfor %}
{% endif %}

{% if pip_packages is defined %}
RUN pip install {% for pip_package in pip_packages %}{{ pip_package }} {% endfor %}
{% endif %}

# drop back to the regular jenkins user
USER jenkins

ENV JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
WORKDIR /var/jenkins_home

COPY security.groovy /usr/share/jenkins/ref/init.groovy.d/security.groovy
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt

RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt
